version: '3.4'

services:    
  nintendoshop.catalog.db:
    image: 'mongo'
    restart: always
    container_name: 'nintendoshop.catalog.db'
    environment:
      MONGO_INITDB_DATABASE : nintendoshop.catalog.db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: 'mongo-express'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo
      
  nintendoshop.catalog:
    image: ${DOCKER_REGISTRY-}nintendoshopcatalog
    build:
      context: .
      dockerfile: NintendoShop.Catalog/Dockerfile
    depends_on:
      - nintendoshop.catalog.db